<?php
$a = 20; // المتغير الأول
$b = 3;  // المتغير الثاني

echo "Summation: " . ($a + $b) . "<br>";     // عملية الجمع
echo "Subtraction: " . ($a - $b) . "<br>";   // عملية الطرح
echo "Multiplication: " . ($a * $b) . "<br>";// عملية الضرب
echo "Division: " . ($a / $b) . "<br>";      // عملية القسمة
echo "Modulus: " . ($a % $b) . "<br>";       // باقي قسمة $a على $b (الناتج 2)
echo "Exponentiation: " . ($a ** 3) . "<br>";// الأسس: 20 أُس 3 (الناتج 8000)
?>